### ISSUE TITLE
remove_dummy_index function in Tensor class

### ISSUE THREAD

**Issue by key262yek** [andrewdarmawan/tncontract#12]
490     def remove_dummy_index(self, label):
 491         """Remove the first dummy index (that is, an index of dimension 1) 
 492         with specified label."""
 493         if not self.index_dimension('label'==1):
 494             # index not a dummy index
 495             raise ValueError("Index specified is not a dummy index.")
 496         self.move_index(label, 0)
 497         self.labels = self.labels[1:]
 498         self.data = self.data[0]

This is the code of function 'remove_dummy_index' in your file tensor.py. 
I think the line 493 does not work well. 
It always carry False boolean to index_dimension function.

**Comment by key262yek** [comment]
And by structure of 'set_labels' function
data must be changed first

**Comment by andrewdarmawan** [comment]
This function is broken, thanks for pointing it out. It's also not very useful, so I've removed it. You should be able to use the method 'remove_all_dummy_indices' (in which you can specify a particular label to remove) to do what the 'remove_dummy_index' method was originally intended to do.
