### ISSUE TITLE
Change in behaviour of `tensor_svd` breaks `left_canonise` (and others)

### ISSUE THREAD

**Issue by arnelg** [andrewdarmawan/tncontract#7]
`tensor_svd` has changed its behavior w.r.t the labels returned ("svd_out" is now "svdout" by default etc.). This breaks functions that assumes the old behavior. The functions that appear to be affected are
- `left_canonise`
- `swap_gate`
- `tensor_to_mps`
- `tensor_to_mpo`

Another issue is that `truncated_svd` is a bit different than `tensor_svd`. Do we need both, or can `tensor_svd` be augmented with appropriate keywords to take over for `truncated_svd`?

**Comment by andrewdarmawan** [comment]
Indeed, I fixed this at uni but forgot to push the change, sorry. Simply need to change the default keyword argument to svd_label="svd_". Yes I think it would make sense to remove truncated_svd and have tensor_svd truncate when chi, and threshold arguments are set.

**Comment by arnelg** [comment]
Okay, wasn't sure if you preferred changing the default to "svd_" or changing to "svdout" etc. everywhere else.. (Either change is pretty trivial to do). I'll just fix it locally and wait for your push later.

**Comment by andrewdarmawan** [comment]
I also changed the other functions which use tensor_svd to generate a unique label for svd_label using unique _label() (so as to avoid any potential conflict with user supplied labels, e.g. if the input to tensor_svd has its own label called "svd_in").  I felt this would be safest, what do you think?

**Comment by arnelg** [comment]
Yeah that seems like a good idea. I guess that could be a good general convention to follow whenever there is a "temporary" label only existing in the scope of a function or similar.

**Comment by andrewdarmawan** [comment]
Fixed as described above.
