### ISSUE TITLE
canonise vs canonize vs canonicalize

### ISSUE THREAD

**Issue by andrewdarmawan** [andrewdarmawan/tncontract#9]
According to wikipedia, the verb " to put something in canonical form" is "to canonicalize",  https://en.wikipedia.org/wiki/Canonical_form

However, it seems that in other contexts "to canonize" is used
https://en.wikipedia.org/wiki/Graph_canonization
Schollwock also uses "to canonize".

Any suggestions on which convention to choose? It would be better to choose now, rather than later.

**Comment by arnelg** [comment]
I like the shorter canonise/ze. I usually try to write American English myself, i.e. I would use the -ze ending, but I don't have any strong preference.

**Comment by andrewdarmawan** [comment]
OK I'll keep it as canonise for now.
